### ISSUE TITLE
Remove rt_weapons_maps cvar.

### ISSUE THREAD

**Issue by ufame** [ufame/ReviveTeammates#4]
Remove cvar [rt_weapons_maps](https://github.com/ufame/ReviveTeammates/blob/552d6e6e17c0e377fb1040ae4572ba532fabe475/addons/amxmodx/scripting/rt_bonus.sma#L117)
Use ['configs/maps' ](https://dev-cs.ru/threads/608/) if necessary

**Comment by Albertinko** [comment]
@ufame ЧТО ТЫ НАДЕЛАЛ

**Comment by Albertinko** [comment]
@Albertinko Delete
